name: NCP-CI

on:
  push:
    branches:
      main
      
jobs:
  CI:
    runs-on: ubuntu-18.04
    
    steps:
      # 체크아웃 및 JDK 세팅
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      # 테스트를 제외하고 빌드
      - name: Build with Maven
        run: mvn package
        shell: bash
