name: NCP CD

on:
  push:
    branches:
      main
      
jobs:
  CD:
    runs-on: ubuntu-18.04
    
    steps:
      # 체크아웃 및 JDK 세팅
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      # SSH로 접속
      - name: Deploy to Prod
        uses: appleboy/ssh-action@master
        id: deploy-main
        with:
          host: ${{ secrets.NCP_PROD_SERVER_IP }}
          username: ${{ secrets.NCP_PROD_SERVER_USER }}
          password: ${{ secrets.NCP_PROD_SERVER_PASSWORD }}
          port: ${{ secrets.NCP_PROD_SERVER_SSH_PORT }}
          script: |
            bash /home/scripts/stop.sh
            cd /home/mybox
            git pull
            mvn package
            nohup java -jar ./target/mybox-0.0.1-SNAPSHOT.jar 1> nohup/stdout.txt 2> nohup/stderr.txt &
            
